name: Mateusz Haligowski
description: personal site & blog
url: http://mhaligowski.github.io
markdown: kramdown
highlighter: rouge
gravatar_url: https://www.gravatar.com/avatar/106bc4d1c66b41a5c98636ab0fb2771e
github_username: mhaligowski
twitter_username: mhaligowski
linkedin_username: mhaligowski
resume_url: https://dl.dropboxusercontent.com/u/9035816/Mateusz%20Haligowski%20CV%20%5Ben%5D.pdf
