name: Mateusz Haligowski
description: personal site & blog
markdown: redcarpet
pygments: true
gravatar_url: http://www.gravatar.com/avatar/106bc4d1c66b41a5c98636ab0fb2771e
github: mhaligowski
twitter: mhaligowski
linkedin: mhaligowski
